# Generated by Django 5.2.13 on 2026-04-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('typology', models.CharField(max_length=50)),
                ('quantity_formula', models.CharField(help_text='Formula using "panels" e.g., "2 * panels"', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('frame', 'Frame'), ('sash', 'Sash'), ('bead', 'Bead')], max_length=20)),
                ('bar_length', models.FloatField(default=6000)),
                ('cost_per_bar', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='DesignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('window', 'Window'), ('door', 'Door')], default='window', max_length=20)),
                ('width', models.FloatField(help_text='Width in mm')),
                ('height', models.FloatField(help_text='Height in mm')),
                ('typology', models.CharField(choices=[('sliding', 'Sliding'), ('casement', 'Casement'), ('fixed', 'Fixed')], max_length=20)),
                ('glass_type', models.CharField(max_length=100)),
                ('finish', models.CharField(max_length=100)),
                ('mesh', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='CutPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(help_text='Length in mm')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_pieces', to='core.designitem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
