# Generated by Django 5.2.13 on 2026-05-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardBarLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
            ],
        ),
    ]
