# Generated by Django 5.2.13 on 2026-05-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_standardbarlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='price_per_unit',
            field=models.FloatField(default=0),
        ),
    ]
