# Generated by Django 5.2.13 on 2026-05-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hardware_price_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glass_type', models.CharField(max_length=100, unique=True)),
                ('price_per_sqm', models.FloatField(default=0)),
            ],
        ),
    ]
