# Generated by Django 5.2.13 on 2026-05-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_glassrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='designitem',
            name='number_of_panels',
            field=models.IntegerField(default=1),
        ),
    ]
